src/data_exporting/gremlinImpl.ts
src/data_importing/httpImpl.ts

corrected erroneous config calls

correction on encryption key secret

---

readme.md
src/api/data_source_routes.ts
src/api/graph_routes.ts
src/api/metatype_relationship_pair_routes.ts
src/api/metatype_relationship_routes.ts
src/api/metatype_routes.ts
src/api/middleware.ts
src/migrate.ts

Correction of a compiler bug when dealing with string to number conversion. Because there is no way for that to ever error out, I put ignore statements above the offending lines and documented the behavior. 
I also updated the readme and migration script in a small way.
This caused compilation errors when attempting to run the project.
Ran all suite tests, ran migration on raw database.
- [ x] My code follows the code style of this project.

bugfix on compiler error

---

.env-sample
api_documentation/Core.postman_collection.json
api_documentation/Core.swagger_collection.json
migrations/022_files_container_id.sql
package-lock.json
package.json
src/api/data_source_routes.ts
src/api_handlers/data_source.ts
src/config.ts
src/data_query/readme.md
src/data_query/resolvers.ts
src/data_query/schema.ts
src/data_query/types.ts
src/data_storage/file_filter.ts
src/data_storage/file_storage.ts
src/file_storage/azure_blob_impl.ts
src/file_storage/file_storage.ts
src/file_storage/filesystem_impl.ts
src/file_storage/mock_impl.ts
src/test/file_storage/azure_blob_imp.spec.ts
src/test/file_storage/filesystem_impl.spec.ts
src/test/files/storage.spec.ts
src/types/fileT.ts

I added the ability to query uploaded files through the normal querying route. This follows all the GraphQL standards and the patterns already setup as part of the graph querying portion (nodes & edges). I added new types to the schema and data query folder, as well as new resolvers for files. 
I also added the ability for someone to download a file using Deep Lynx. This file downloading was completed for both file system and Azure Blob Storage.
This was forgotten when doing the original querying work. This is also needed quickly so that NC State can accomplish their goals
- ran `npm run test` - all are passing
- used Postman and browser to test the new file downloading and querying endpoints

File Storage Query & Download

---

migrations/023_metatypekeys_metatyperelationship_keys.sql
src/api/metatype_routes.ts
src/data_importing/readme.md
src/data_storage/graph/edge_storage.ts
src/data_storage/graph/node_storage.ts
src/data_storage/import/import_storage.ts
src/data_storage/metatype_filter.ts
src/data_storage/metatype_key_storage.ts
src/data_storage/metatype_relationship_key_storage.ts
src/data_storage/postgresStorage.ts
src/file_storage/mock_impl.ts
src/test/nodes/storage.spec.ts
src/types/metatype_keyT.ts
src/types/metatype_relationship_keyT.ts
src/utilities.ts
tools/ontology_extractor/extractor.js

This PR consists of multiple changes across multiple systems, all relating back to individual issues. See description for details.
Closes #17 - mock file storage now considered depcrated
Closes #4 - filtering can be accomplished with a `Filter` class extension
Closes #7 - no idea what I meant by "extendible", with more of the application finished this issue no longer makes sense and should be closed
Closes #12 - added default value and regex functionality to metatype key and metatype relationship keys
Closes #19 - rewrote the issue 
Closes #6 - `io-ts` errors now greatly simplified
General cleanup needed of the Deep Lynx program.
Test suite runs correctly.

General Issue Completion

---

api_documentation/Core.postman_collection.json
src/api/user_routes.ts

Adds routes for editing/updating existing users and permanently deleting users. Updated Postman docs accordingly.
Tested through Postman and UI

Add routes for editing and deleting users

---

src/api/container_routes.ts
src/api/middleware.ts
src/api/router.ts
src/api/user_routes.ts
src/api_handlers/container.ts
src/user_management/authorization/authorization.ts
src/user_management/users.ts

Modified route permissions to allow user signup without being authed. Corrected various authentication issues.
Testing suite and used the UI to verify other aspects of login behavior.

User Registration, Auth Corrections

---

src/data_query/resolvers.ts
src/data_storage/import/container_import.ts

Fixes the container creation functionality in container import to use the correct create statement to add the needed policies. Also changes the GraphQL resolver to return correctly formatted Property values.

Fix container import

---

src/api/container_routes.ts
src/api/oauth_routes.ts
src/data_storage/import/container_import.ts
src/services/oauth/oauth.ts
web_ui/src/api/client.ts
web_ui/src/components/logout.vue
web_ui/src/components/newContainerDialog.vue
web_ui/src/pages/ContainerSelect.vue
web_ui/src/pages/Login.vue
web_ui/src/translations.ts

Created the ability to import a container through the Admin UI. Involved hooking up to the backend import endpoint. Also ran a linter on the ontology import function - as that was never linted before.
Also a few bug fixes for the authentication system.
Test suite continues to pass and tested the frontend functionality myself.

added container import, fixed bugs

---

.env-sample
src/config.ts
src/data_exports.ts
src/data_polling.ts
src/data_processing.ts
src/data_processing/processing.ts
src/main.ts
tslint.json

Pulled out long running processes and turned them into their own files. This allows use to spawn child processes and take advantage of multiple CPU threads. This is the first step in refactoring the Data Source processing route and functionality. Future changes will most likely utilize the queue and process pattern found in the upcoming event system.
Test suite passes and application functions as expected.

pulled out some processes and made them children

---

src/data_query/resolvers.ts

Fix node property object representation

---

package-lock.json
package.json

updated for security purposes

---

web_ui/src/components/transformationDialog.vue

hotfix to the clearable Root Array selection

root array clearable

---

migrations/034_unique_container_constraint.sql
src/api_handlers/container.ts
src/config.ts
src/services/oauth/oauth.ts
src/user_management/users.ts
web_ui/src/auth/authentication_service.ts
web_ui/src/components/importDataDialog.vue
web_ui/src/pages/Home.vue

Corrected an issue with container name uniqueness - now two users can have containers with the same name.
Corrected UI bug with permissions not being applied correctly to menu choices.
Corrected User not being encoded into the JWT with permissions.
Corrected various permission issues.
General bugfixes
Test suite ran, UI tested.

general bugfixes

---

migrations/035_unique_event_constraint.sql

Adds two unique constraints to the registered_events table to ensure that applications cannot register for any combination of container/datasource and event type more than once.

Adds constraints to ensure uniqueness of registered events

---

api_documentation/Core.postman_collection.json

Updated the Postman collection JSON:
1. removed the legacy login requests
2. replaced with GET oath/token
3. added bearer environment variable to root
4. added auth inheritance in subdirectories
Postman collection was out of date with new oauth routes
Opened saved .JSON file in Postman

Updated Postman collection to reflect new oauth routes

---

.env-sample
src/config.ts
src/data_importing/httpImpl.ts
src/services/cache/cache.ts
src/test/.env-sample
src/test/cache/cache.spec.ts

Quick PR undoing the stub implementation of caching.

must have some form of caching

---

src/api/oauth_routes.ts
src/services/oauth/oauth.ts

Updated the oAuth service to use the new Promise driven caching interface.
Login was completely broken without being reworked.
Ran suite, ran UI

fixed login caching issue

---

.env-sample
src/api/metatype_relationship_pair_routes.ts
src/api/metatype_relationship_routes.ts
src/api/metatype_routes.ts
src/api_handlers/data_source.ts
src/data_importing/httpImpl.ts
src/data_storage/filter.ts
src/data_storage/import/import_storage.ts
src/data_storage/metatype_key_storage.ts
src/data_storage/metatype_relationship_filter.ts
src/data_storage/metatype_relationship_pair_filter.ts
src/data_storage/metatype_relationship_pair_storage.ts
src/data_storage/metatype_relationship_storage.ts
src/data_storage/metatype_storage.ts
src/migrate.ts
src/test/.env-sample
web_ui/src/api/client.ts
web_ui/src/components/transformationDialog.vue
web_ui/src/translations.ts
web_ui/src/views/DataImports.vue
web_ui/src/views/DataMapping.vue
web_ui/src/views/MetatypeRelationshipPairs.vue
web_ui/src/views/MetatypeRelationships.vue
web_ui/src/views/Metatypes.vue

Closes #89 
Closes #102 
Closes #117 
Converted the tables for Metatypes, Metatype Relationships, and Metatype Relationship Pairs to dynamic data tables.
Converted search to dynamic search on new Metatype Relationship Pairs
Updated Axios calls
Added `count` into the filter base class
Created and modified filter classes for Metatypes, Metatype Relationships, and Metatype Relationship Pairs
Bugfix for Metatype Keys not converting correctly on update
Modified `.env-sample` with default `CORE_DB_CONNECTION_STRING` - default is the Docker PostgreSQL instance
Corrected issue with HTTP Data Sources not setting active flag correctly.
Needed better listing and CRUD on Metatypes, Metatype Relationships, and Metatype Relationship Pairs.
UI and Test suite

data tables for metatypes, metatype relationships

---

src/test/data_processing/http_impl.spec.ts

quick update to a failing test

fixed failing test

---

src/data_storage/import/container_import.ts

Update metatype key values in container import

---

.env-sample
src/api_handlers/container.ts
src/api_handlers/user.ts
src/test/.env-sample
src/test/cache/cache.spec.ts
src/test/container_import/storage.spec.ts
src/test/containers/storage.spec.ts
src/test/data_processing/import.spec.ts
src/test/data_processing/storage.spec.ts
src/test/data_processing/type_mapping.spec.ts
src/test/data_processing/type_mapping_storage.spec.ts
src/test/graphs/generate_graph.spec.ts
src/test/gremlin/gremlin.spec.ts
src/user_management/authorization/authorization.ts

Multiple failing tests.
Corrected tests and added sync file reading on container ontology tests.

fixed failing and non-sync tests

---

src/api/views/login.hbs

Changed login failure message to "Incorrect username/password", replacing reference to error object
Closes #98 
Attempted to log in to Deep Lynx at home screen using a username that doesn't exist in the database.
* An incorrect password simply returns the user to the homepage, and no message is shown

updated login failure to readable message

---

src/data_storage/import/container_import.ts
src/test/container_import/storage.spec.ts

These changes correct the container import process and some of the associated tests.
All container import tests pass

Fix container import tests

---

src/api/container_routes.ts
src/api/export_routes.ts
src/api/router.ts
src/data_storage/import/import_storage.ts
src/test/exports/gremlin_storage.spec.ts
web_ui/src/api/types.ts

Quick test cleanup and route and type prep for Export UI changes.
Just needed to get some cleanup out of the way of the main pull request
Test suite ran

cleanup and prep for UI change

---

api_documentation/Core.postman_collection.json
api_documentation/Core.swagger_collection.json
src/api/event_routes.ts

Adds a delete route for registered events

Add route and api docs for deleting a registered event

---

src/data_access_layer/mappers/data_warehouse/ontology/container_import.ts
src/data_warehouse/ontology/metatype_key.ts
src/data_warehouse/ontology/metatype_relationship_key.ts

This fixes issues with creating containers in Deep Lynx from the DIAMOND ontology and updating containers with that ontology. Please note that there are also updates to DIAMOND that are REQUIRED to use DIAMOND with the latest version of Deep Lynx.
Descriptions are no longer required on metatype keys and metatype relationship keys. The container import has been simplified and altered to follow the new structure of using repositories as much as possible.
All tests pass

Update container import to use repositories

---

server/src/data_access_layer/mappers/data_warehouse/ontology/container_mapper.ts
server/src/jobs/process_worker.ts
server/src/tests/data_warehouse/ontology/containers/mapper.spec.ts

- changed to `pg_try_xact_advisory_lock` in order to avoid deadlocks and hanging lock calls
Processing thread was hanging
new test written and tested successfully
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] My code follows the code style of this project.

changed advisory lock to try_xact over just xact

---

server/src/data_access_layer/repositories/data_warehouse/data/report_query_repository.ts

Construct URL for azure blob storage based on endpointSuffix
Gives DataFusion access to object storage on deployed instances
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] My code follows the code style of this project.

added support for endpointSuffix

---

server/NodeLibraries/deeplynx/src/timeseries/azure_object_store.rs

Azurite urls are different in subtle ways to Azure cloud urls. This ensures we handle both.
The Azure library used for getting the query report file size was not updated to correctly handle Azure urls to find the report files. It worked well in Azurite and we fixed it for describe queries. This is similar to the issues datafusion had but it's a separate library to datafusion.
Tested with a azure cloud instance (free tier) and with local azurite to ensure both work.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] My code follows the code style of this project.
-   [x] My change requires a change to the …

Ensure file can be found in both azurite and azure cloud to pull metadata about query report files

---

server/NodeLibraries/deeplynx/package.json
server/package-lock.json
server/package.json
server/yarn.lock
ui/AdminWebApp/package-lock.json
ui/AdminWebApp/package.json
ui/WebGLViewer/package-lock.json
ui/WebGLViewer/package.json

Version bump and package upgrades
Preparation for release to 1.7.0
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] My code follows the code style of this project.

package audit and version bump

---

ui/Next/src/app/(main)/containers/[containerID]/page.tsx
ui/Next/src/app/_wireframe/sidebar.tsx
ui/Next/src/app/_wireframe/wireframe.tsx
ui/Next/src/app/styles.ts

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] My code follows the code style of this project.

Main sidenav styling first pass

---

ui/Next/src/app/(main)/containers/[containerID]/layout.tsx
ui/Next/src/app/(main)/containers/[containerID]/page.tsx
ui/Next/src/app/(main)/containers/page.tsx
ui/Next/src/app/_wireframe/add-container-dialog.tsx
ui/Next/src/app/_wireframe/sidebar.tsx
ui/Next/src/app/_wireframe/wireframe.tsx

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] My code follows the code style of this project.

Add container functionality and container dashboard first pass

---

Dockerfile

Add corepack to dockerfile so builds run properly. 
Corepack wasn't being found during build even though it should be included with nodejs.
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] My code follows the code style of this project.
-   [x] I have updated the documentation accordingly.

Install corepack

---

server/NodeLibraries/deeplynx/src/shape_hasher.rs

docker build fix
built successfully twice with `docker compose build`.
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] My code follows the code style of this project.

attempt docker build fix
